import { test, expect } from '@playwright/test';

test('hierarchy lists filter and both import screens choose the matching bank', async ({page,request}) => {
    test.setTimeout(180000);
    const response = await request.post('/__browser/fixture',{data:{owner:'professional_school',management:true,management_filters:true}});
    expect(response.ok()).toBeTruthy();
    const data = await response.json();
    await page.goto('/login');
    await page.getByLabel('Email',{exact:true}).fill(data.actor_email);
    await page.getByLabel('Password',{exact:true}).fill('password');
    await page.getByRole('button',{name:'Log in',exact:true}).click();
    await page.waitForURL(url=>!url.pathname.startsWith('/login'));
    const base='/professional-schools/'+data.owner_id;
    await page.goto(base+'/programmes');
    await page.getByRole('searchbox',{name:'Search records'}).fill('Programme 2');
    await expect(page.getByRole('cell',{name:'Filter Programme 2',exact:true})).toBeVisible();
    await expect(page.getByRole('cell',{name:'Filter Programme 1',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Clear filters',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Filter Programme 1',exact:true})).toBeVisible();
    await page.goto(base+'/courses');
    await page.getByRole('combobox',{name:'Filter programme',exact:true}).selectOption({label:'Filter Programme 2'});
    await expect(page.getByRole('cell',{name:'Filter Course 2',exact:true})).toBeVisible();
    await expect(page.getByRole('cell',{name:'Filter Course 1',exact:true})).toHaveCount(0);
    await page.goto(base+'/modules');
    await page.getByRole('combobox',{name:'Filter course',exact:true}).selectOption({label:'Filter Course 1'});
    await expect(page.getByRole('cell',{name:'Filter Module 2',exact:true})).toBeVisible();
    await expect(page.getByRole('cell',{name:'Filter Module 3',exact:true})).toHaveCount(0);
    await page.goto(base+'/question-banks');
    await page.getByRole('combobox',{name:'Filter course',exact:true}).selectOption({label:'Filter Course 2'});
    await expect(page.getByRole('cell',{name:'Filter Bank 3',exact:true})).toBeVisible();
    await expect(page.getByRole('cell',{name:'Filter Bank 1',exact:true})).toHaveCount(0);
    await page.goto('/questions');
    await page.getByRole('combobox',{name:'Filter course',exact:true}).selectOption({label:'Filter Course 1'});
    await page.getByRole('combobox',{name:'Filter module',exact:true}).selectOption({label:'Filter Module 2'});
    await expect(page.getByRole('cell',{name:'Filter question 2',exact:true})).toBeVisible();
    await expect(page.getByRole('cell',{name:'Filter question 3',exact:true})).toHaveCount(0);
    await page.getByRole('checkbox',{name:'Select all questions',exact:true}).check();
    await expect(page.getByText('1 of 1 editable questions selected.',{exact:true})).toBeVisible();
    const csv=(stem:string)=>Buffer.from('difficulty,marks,question_text,status,option_a,option_b,correct_answer\nmedium,1,'+stem+',draft,Yes,No,A\n');
    await page.getByRole('combobox',{name:'Import course',exact:true}).selectOption({label:'Filter Course 1'});
    await page.getByRole('combobox',{name:'Import module',exact:true}).selectOption({label:'Filter Module 2'});
    const picker=page.getByRole('combobox',{name:'Import question bank',exact:true});
    await expect(picker.locator('option')).toHaveCount(2);
    await picker.selectOption(data.filter_bank_ids[1]);
    await page.getByRole('combobox',{name:'Import course',exact:true}).selectOption({label:'Filter Course 2'});
    await expect(picker).toHaveValue('');
    await expect(page.getByRole('combobox',{name:'Import module',exact:true})).toHaveValue('');
    await page.getByRole('combobox',{name:'Import course',exact:true}).selectOption({label:'Filter Course 1'});
    await page.getByRole('combobox',{name:'Import module',exact:true}).selectOption({label:'Filter Module 2'});
    await picker.selectOption(data.filter_bank_ids[1]);
    await page.getByLabel('Upload CSV',{exact:true}).setInputFiles({name:'questions.csv',mimeType:'text/csv',buffer:csv('Global imported question')});
    await page.getByRole('button',{name:'Upload',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Global imported question',exact:true})).toBeVisible({timeout:30000});
    await page.goto(base+'/questions');
    await page.getByRole('combobox',{name:'Import course',exact:true}).selectOption({label:'Filter Course 2'});
    await page.getByRole('combobox',{name:'Import module',exact:true}).selectOption({label:'Filter Module 3'});
    await page.getByRole('combobox',{name:'Import question bank',exact:true}).selectOption(data.filter_bank_ids[2]);
    await page.getByLabel('CSV File',{exact:true}).setInputFiles({name:'questions.csv',mimeType:'text/csv',buffer:csv('Professional imported question')});
    await page.getByRole('button',{name:'Import Questions',exact:true}).click();
    await expect(page.getByRole('cell',{name:'Professional imported question',exact:true})).toBeVisible({timeout:30000});
    await page.getByRole('combobox',{name:'Filter question bank',exact:true}).selectOption({label:'Filter Bank 3'});
    await expect(page.getByRole('cell',{name:'Global imported question',exact:true})).toHaveCount(0);
});
