import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Printer } from 'lucide-react';
import type { ReactNode } from 'react';
import { PageHeader, PortalAppShell, StatusBadge } from '@/Components/Platform';
import { Button } from '@/Components/ui/button';

type Summary = {
    total_candidates: number;
    logged_in: number;
    active: number;
    submitted: number;
    disconnected: number;
    disqualified: number;
    suspicious: number;
};

type CandidateRow = {
    attempt_id: string;
    candidate_name: string;
    registration_number: string;
    status: string;
    progress: number;
    answered_questions: number;
    total_questions: number;
    login_time?: string | null;
    suspicious_event_count: number;
    ip_address?: string | null;
};

type EventItem = {
    id: string;
    candidate_name?: string | null;
    registration_number?: string | null;
    event_type: string;
    severity: string;
    source?: string | null;
    snapshot_url?: string | null;
    occurred_at?: string | null;
    payload?: Record<string, unknown>;
};

type FeedItem = {
    id: string;
    type: string;
    candidate_name?: string | null;
    registration_number?: string | null;
    message: string;
    occurred_at?: string | null;
};

export default function IncidentReport({ exam, supervisor, summary, rows, events, feed, generatedAt }: { exam: { id: string; title: string; exam_code: string; status: string; starts_at?: string | null; ends_at?: string | null; duration_minutes: number }; supervisor: { name: string; email: string }; summary: Summary; rows: CandidateRow[]; events: EventItem[]; feed: FeedItem[]; generatedAt: string }) {
    return (
        <PortalAppShell title="Incident Report">
            <Head title={`${exam.title} Incident Report`} />
            <section className="mx-auto max-w-7xl print:max-w-none">
                <PageHeader
                    eyebrow="Supervisor Report"
                    title="Incident Report"
                    description={`${exam.title} | ${exam.exam_code}`}
                    actions={<div className="flex flex-wrap gap-2 print:hidden"><Button asChild type="button" variant="secondary"><Link href={`/exams/${exam.id}/monitor`}><ArrowLeft className="h-4 w-4" />Monitor</Link></Button><Button type="button" onClick={() => window.print()}><Printer className="h-4 w-4" />Print</Button></div>}
                />

                <div className="grid gap-4 md:grid-cols-4">
                    <Info label="Generated By" value={`${supervisor.name} (${supervisor.email})`} />
                    <Info label="Generated At" value={formatDateTime(generatedAt)} />
                    <Info label="Exam Window" value={`${formatDateTime(exam.starts_at)} - ${formatDateTime(exam.ends_at)}`} />
                    <Info label="Duration" value={`${exam.duration_minutes} minutes`} />
                </div>

                <div className="mt-6 grid gap-4 md:grid-cols-4 xl:grid-cols-7">
                    {Object.entries(summary).map(([key, value]) => <Metric key={key} label={key.replaceAll('_', ' ')} value={value} />)}
                </div>

                <ReportTable title="Candidate Attendance And Status" headers={['Candidate', 'Registration', 'Status', 'Progress', 'Answered', 'Incidents', 'IP Address']}>
                    {rows.map((row) => (
                        <tr key={row.attempt_id}>
                            <td className="py-3 font-semibold">{row.candidate_name}</td>
                            <td>{row.registration_number}</td>
                            <td><StatusBadge label={row.status.replaceAll('_', ' ')} tone={row.status === 'disqualified' ? 'danger' : row.status === 'active' ? 'success' : 'neutral'} /></td>
                            <td>{row.progress}%</td>
                            <td>{row.answered_questions}/{row.total_questions}</td>
                            <td>{row.suspicious_event_count}</td>
                            <td>{row.ip_address ?? 'N/A'}</td>
                        </tr>
                    ))}
                </ReportTable>

                <ReportTable title="Anti-Cheating Incidents" headers={['Time', 'Candidate', 'Registration', 'Event', 'Severity', 'Evidence', 'Details']}>
                    {events.length === 0 && <tr><td colSpan={7} className="py-6 text-center text-slate-500">No incidents recorded.</td></tr>}
                    {events.map((event) => (
                        <tr key={event.id}>
                            <td className="py-3 text-slate-500">{formatDateTime(event.occurred_at)}</td>
                            <td className="font-semibold">{event.candidate_name ?? 'N/A'}</td>
                            <td>{event.registration_number ?? 'N/A'}</td>
                            <td>{event.event_type.replaceAll('_', ' ')}</td>
                            <td>{event.severity}</td>
                            <td>{event.snapshot_url ? <a className="text-primary underline" href={event.snapshot_url} target="_blank" rel="noreferrer">Evidence</a> : 'None'}</td>
                            <td className="max-w-md truncate">{event.payload ? JSON.stringify(event.payload) : 'N/A'}</td>
                        </tr>
                    ))}
                </ReportTable>

                <ReportTable title="Supervisor And System Activity" headers={['Time', 'Type', 'Candidate', 'Registration', 'Message']}>
                    {feed.map((item) => (
                        <tr key={item.id}>
                            <td className="py-3 text-slate-500">{formatDateTime(item.occurred_at)}</td>
                            <td>{item.type.replaceAll('_', ' ')}</td>
                            <td className="font-semibold">{item.candidate_name ?? 'System'}</td>
                            <td>{item.registration_number ?? 'N/A'}</td>
                            <td>{item.message}</td>
                        </tr>
                    ))}
                </ReportTable>
            </section>
        </PortalAppShell>
    );
}

function Info({ label, value }: { label: string; value: string }) {
    return <div className="rounded-md border border-border bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-2 text-sm font-semibold text-slateDark">{value}</div></div>;
}

function Metric({ label, value }: { label: string; value: number }) {
    return <div className="rounded-md border border-border bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold text-slateDark">{value}</div></div>;
}

function ReportTable({ title, headers, children }: { title: string; headers: string[]; children: ReactNode }) {
    return <section className="mt-6 rounded-md border border-border bg-white p-5 shadow-sm"><h2 className="font-semibold text-slateDark">{title}</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{headers.map((header) => <th key={header} className="py-2">{header}</th>)}</tr></thead><tbody className="divide-y divide-border">{children}</tbody></table></div></section>;
}

function formatDateTime(value?: string | null): string {
    return value ? new Date(value).toLocaleString() : 'N/A';
}
