<?php

namespace App\Http\Controllers;

use App\Models\CandidateExamAttempt;
use App\Models\CandidatePerformanceProfile;
use App\Models\Exam;
use App\Models\User;
use App\Services\ResultManagementService;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response as InertiaResponse;

class ResultController extends Controller
{
    public function __construct(private readonly ResultManagementService $results)
    {
    }

    public function index(Request $request): InertiaResponse
    {
        $exams = $this->examScope($request->user(), $request->route('organization'))
            ->withCount(['attempts as submitted_attempts_count' => fn ($query) => $query->whereIn('status', [
                CandidateExamAttempt::STATUS_SUBMITTED,
                CandidateExamAttempt::STATUS_AUTO_SUBMITTED,
            ])])
            ->latest()
            ->get()
            ->map(fn (Exam $exam) => [
                'id' => $exam->id,
                'title' => $exam->title,
                'exam_code' => $exam->code,
                'status' => $exam->status,
                'submitted_attempts_count' => $exam->submitted_attempts_count,
                'total_marks' => $exam->total_marks,
                'pass_mark' => $exam->pass_mark,
            ]);

        $attempts = CandidateExamAttempt::query()
            ->whereIn('exam_id', $exams->pluck('id'))
            ->whereIn('status', [CandidateExamAttempt::STATUS_SUBMITTED, CandidateExamAttempt::STATUS_AUTO_SUBMITTED])
            ->with(['candidate', 'exam', 'answers.subject', 'proctoringEvents'])
            ->get();

        return Inertia::render('Results/Index', [
            'exams' => $exams,
            'dashboard' => $this->results->dashboard($attempts),
        ]);
    }

    public function show(Request $request, Exam $exam): InertiaResponse
    {
        $this->authorizeExam($request->user(), $exam);
        $attempts = $this->results->queryForExam($exam)->get();
        $rows = $attempts->map(fn (CandidateExamAttempt $attempt) => $this->results->row($attempt))->values();

        return Inertia::render('Results/Exam', [
            'exam' => [
                'id' => $exam->id,
                'title' => $exam->title,
                'exam_code' => $exam->code,
                'total_marks' => $exam->total_marks,
                'pass_mark' => $exam->pass_mark,
            ],
            'rows' => $rows,
            'dashboard' => $this->results->dashboard($attempts),
            'adaptive_analysis' => $this->examAdaptiveAnalysis($exam),
        ]);
    }

    public function candidate(Request $request, CandidateExamAttempt $attempt): InertiaResponse
    {
        $attempt->loadMissing(['exam', 'candidate', 'answers.question.options', 'answers.subject', 'papers.question.options', 'papers.question.subject', 'papers.question.questionBank', 'proctoringEvents']);
        $this->authorizeExam($request->user(), $attempt->exam);

        return Inertia::render('Results/Candidate', [
            'result' => $this->results->row($attempt),
            'answers' => $this->markedPaperRows($attempt, $request->user()),
            'adaptive' => $this->candidateAdaptiveAnalysis($attempt),
        ]);
    }

    public function exportCsv(Request $request, Exam $exam)
    {
        $this->authorizeExam($request->user(), $exam);
        $rows = $this->results->queryForExam($exam)->get()->map(fn (CandidateExamAttempt $attempt) => $this->results->row($attempt));

        return Response::make($this->results->csv($rows), 200, [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="'.$exam->code.'-results.csv"',
        ]);
    }

    public function exportPdf(Request $request, Exam $exam)
    {
        $this->authorizeExam($request->user(), $exam);
        $exam->loadMissing(['organization', 'school', 'center']);
        $attempts = $this->results->queryForExam($exam)->get();
        $dashboard = $this->results->dashboard($attempts);
        $rows = $attempts->map(fn (CandidateExamAttempt $attempt) => $this->results->row($attempt))->values();
        $lines = [
            'AlignEx Examination Result Summary',
            'Organization: '.($exam->organization?->name ?? 'N/A'),
            'School: '.($exam->school?->name ?? 'N/A'),
            'Center: '.($exam->center?->name ?? 'N/A'),
            'Generated By: '.$request->user()->name.' ('.$request->user()->email.')',
            'Exam: '.$exam->title,
            'Code: '.$exam->code,
            'Submitted Candidates: '.$dashboard['summary']['total'],
            'Passed: '.$dashboard['summary']['passed'],
            'Failed: '.$dashboard['summary']['failed'],
            'Average Percentage: '.$dashboard['summary']['average_percentage'].'%',
            'Generated: '.now()->toDateTimeString(),
            '',
            'Candidate Performance Table',
            sprintf('%-24s %-16s %8s %8s %6s %-8s %-10s %s', 'Candidate', 'Reg. No.', 'Score', 'Percent', 'Grade', 'Status', 'Duration', 'Hash'),
            str_repeat('-', 112),
        ];

        foreach ($rows as $row) {
            $lines[] = sprintf(
                '%-24s %-16s %8s %7s%% %6s %-8s %-10s %s',
                str($row['candidate_name'])->limit(24, '')->toString(),
                str($row['registration_number'])->limit(16, '')->toString(),
                $row['score'].'/'.$row['total_marks'],
                $row['percentage'],
                $row['grade'],
                $row['status'],
                $row['duration_used'],
                $row['result_hash']
            );
        }

        return Response::make($this->results->pdf('AlignEx Result Export', $lines), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="'.$exam->code.'-result-summary.pdf"',
        ]);
    }

    public function markedPaperPdf(Request $request, CandidateExamAttempt $attempt)
    {
        $attempt->loadMissing(['exam.organization', 'exam.school', 'exam.center', 'candidate', 'answers.question.options', 'answers.subject', 'papers.question.options', 'papers.question.subject', 'papers.question.questionBank', 'proctoringEvents']);
        $this->authorizeExam($request->user(), $attempt->exam);

        abort_unless(in_array($attempt->status, [CandidateExamAttempt::STATUS_SUBMITTED, CandidateExamAttempt::STATUS_AUTO_SUBMITTED], true), 404);

        $result = $this->results->row($attempt);
        $lines = [
            'AlignEx Detailed Marked Question Paper',
            'Organization: '.($attempt->exam?->organization?->name ?? 'N/A'),
            'School: '.($attempt->exam?->school?->name ?? 'N/A'),
            'Center: '.($attempt->exam?->center?->name ?? 'N/A'),
            'Generated By: '.$request->user()->name.' ('.$request->user()->email.')',
            'Exam: '.$attempt->exam?->title.' ('.$attempt->exam?->code.')',
            'Candidate: '.trim(($attempt->candidate?->first_name ?? '').' '.($attempt->candidate?->last_name ?? '')),
            'Registration Number: '.$attempt->candidate?->candidate_number,
            'Score: '.$result['score'].'/'.$result['total_marks'].' | '.$result['percentage'].'% | '.$result['status'],
            'Submitted At: '.($attempt->submitted_at?->toDateTimeString() ?? 'N/A'),
            'Verification Hash: '.$result['result_hash'],
            '',
        ];

        foreach ($this->markedPaperRows($attempt, $request->user()) as $index => $row) {
            $lines[] = 'Q'.($index + 1).' ['.$row['subject'].'] Score: '.($row['score_awarded'] ?? '0.00').'/'.$row['marks'];
            $lines[] = 'Question: '.$row['question'];
            foreach ($row['options'] as $option) {
                $markers = [];
                if ($option['selected']) {
                    $markers[] = 'Selected';
                }
                if ($option['correct']) {
                    $markers[] = 'Correct';
                }
                $lines[] = '  '.$option['label'].'. '.$option['option_text'].($markers === [] ? '' : ' ['.implode(', ', $markers).']');
            }
            $lines[] = 'Candidate Answer: '.($row['selected_labels'] ?: 'Not answered');
            $lines[] = 'Correct Answer: '.($row['correct_labels'] ?: 'N/A');
            if ($row['explanation']) {
                $lines[] = 'Explanation: '.$row['explanation'];
            }
            $lines[] = '';
        }

        return Response::make($this->results->pdf('AlignEx Marked Paper', $lines), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="'.$attempt->candidate?->candidate_number.'-'.$attempt->exam?->code.'-marked-paper.pdf"',
        ]);
    }

    public function selfResult(): InertiaResponse
    {
        return Inertia::render('Results/Self');
    }

    public function verification(): InertiaResponse
    {
        return Inertia::render('Results/Verify');
    }

    public function verify(Request $request)
    {
        $data = $request->validate(['hash' => ['required', 'string']]);
        $attempt = CandidateExamAttempt::query()
            ->where('result_hash', strtoupper(trim($data['hash'])))
            ->with(['candidate', 'exam', 'answers.subject', 'proctoringEvents'])
            ->first();

        return response()->json([
            'valid' => (bool) $attempt,
            'result' => $attempt ? $this->results->row($attempt) : null,
        ]);
    }

    public function candidateResult(Request $request)
    {
        $data = $request->validate([
            'exam_code' => ['required', 'string'],
            'identifier' => ['required', 'string'],
        ]);

        $exam = Exam::query()->where('code', strtoupper(trim($data['exam_code'])))->first();

        if (! $exam || ! $this->candidateResultAllowed($exam)) {
            throw ValidationException::withMessages(['exam_code' => 'Result is not available for this exam.']);
        }

        $candidate = $exam->candidates()
            ->where(fn ($query) => $query
                ->where('candidate_number', trim($data['identifier']))
                ->orWhere('phone', trim($data['identifier']))
                ->orWhere('email', trim($data['identifier'])))
            ->first();

        if (! $candidate) {
            throw ValidationException::withMessages(['identifier' => 'Candidate result was not found.']);
        }

        $attempt = CandidateExamAttempt::query()
            ->where('exam_id', $exam->id)
            ->where('candidate_id', $candidate->id)
            ->whereIn('status', [CandidateExamAttempt::STATUS_SUBMITTED, CandidateExamAttempt::STATUS_AUTO_SUBMITTED])
            ->with(['candidate', 'exam', 'answers.subject', 'proctoringEvents'])
            ->first();

        if (! $attempt) {
            throw ValidationException::withMessages(['identifier' => 'Candidate result was not found.']);
        }

        return response()->json(['result' => $this->results->row($attempt)]);
    }

    private function examScope(User $user, mixed $organization = null): Builder
    {
        return Exam::query()
            ->when($organization, fn (Builder $query) => $query->where('organization_id', $organization->id))
            ->when(! $user->isSuperAdmin(), function (Builder $query) use ($user): void {
                $query->where(function (Builder $inner) use ($user): void {
                    $inner->whereRaw('1 = 0')
                        ->when($user->organization_id, fn ($scope) => $scope->orWhere('organization_id', $user->organization_id))
                        ->when($user->school_id, fn ($scope) => $scope->orWhere('school_id', $user->school_id))
                        ->when($user->center_id, fn ($scope) => $scope->orWhere('center_id', $user->center_id))
                        ->when($user->secondary_school_id, fn ($scope) => $scope->orWhere('secondary_school_id', $user->secondary_school_id))
                        ->when($user->professional_school_id, fn ($scope) => $scope->orWhere('professional_school_id', $user->professional_school_id))
                        ->when($user->cbt_center_id, fn ($scope) => $scope->orWhere('cbt_center_id', $user->cbt_center_id));
                });
            })
            ->when($user->isTeacher(), fn (Builder $query) => $query->whereHas('examSubjects', fn (Builder $subjectQuery) => $subjectQuery->whereIn('subject_id', $user->assignedSubjects()->select('subjects.id'))))
            ->when($user->isFacilitator(), fn (Builder $query) => $query
                ->where('exam_category', Exam::CATEGORY_ASSESSMENT)
                ->whereHas('examSubjects.questionBank', fn (Builder $bankQuery) => $this->scopeFacilitatorQuestionBanks($bankQuery, $user)));
    }

    private function authorizeExam(User $user, Exam $exam): void
    {
        abort_unless($this->examScope($user)->whereKey($exam->id)->exists(), 403);
    }

    private function candidateResultAllowed(Exam $exam): bool
    {
        return (bool) data_get($exam->settings ?? [], 'show_result_immediately', false)
            || in_array(data_get($exam->result_release_settings ?? [], 'release_mode'), ['public', 'automatic', 'released'], true);
    }

    /**
     * @return array<string, mixed>
     */
    private function candidateAdaptiveAnalysis(CandidateExamAttempt $attempt): array
    {
        $profiles = CandidatePerformanceProfile::query()
            ->where('candidate_id', $attempt->candidate_id)
            ->where('exam_id', $attempt->exam_id)
            ->with(['subject', 'topic'])
            ->get();

        return [
            'weaknesses' => $profiles
                ->where('mastery_level', CandidatePerformanceProfile::MASTERY_WEAK)
                ->sortBy('score_percentage')
                ->values()
                ->map(fn (CandidatePerformanceProfile $profile) => $this->profileRow($profile))
                ->all(),
            'topic_mastery' => $profiles
                ->sortBy([['subject.name', 'asc'], ['topic.name', 'asc']])
                ->values()
                ->map(fn (CandidatePerformanceProfile $profile) => $this->profileRow($profile))
                ->all(),
            'difficulty_performance' => $this->difficultyPerformance($profiles),
            'recommended_practice_areas' => $this->recommendations($profiles),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function examAdaptiveAnalysis(Exam $exam): array
    {
        $profiles = CandidatePerformanceProfile::query()
            ->where('exam_id', $exam->id)
            ->with(['subject', 'topic'])
            ->get();

        return [
            'topic_mastery' => $this->aggregateProfiles($profiles, ['subject_id', 'topic_id']),
            'difficulty_performance' => $this->difficultyPerformance($profiles),
            'recommended_practice_areas' => $this->recommendations($profiles),
        ];
    }

    /**
     * @param \Illuminate\Support\Collection<int, CandidatePerformanceProfile> $profiles
     * @return array<int, array<string, mixed>>
     */
    private function aggregateProfiles($profiles, array $keys): array
    {
        return $profiles
            ->groupBy(fn (CandidatePerformanceProfile $profile) => collect($keys)->map(fn ($key) => $profile->{$key} ?? 'none')->implode('|'))
            ->map(function ($group) {
                $first = $group->first();
                $percentage = round($group->avg(fn (CandidatePerformanceProfile $profile) => (float) $profile->score_percentage), 2);

                return [
                    'subject' => $first?->subject?->name ?? 'General',
                    'topic' => $first?->topic?->name ?? 'Unspecified topic',
                    'difficulty' => $first?->difficulty ?? 'mixed',
                    'total_questions' => $group->sum('total_questions'),
                    'correct_answers' => $group->sum('correct_answers'),
                    'score_percentage' => $percentage,
                    'mastery_level' => app(\App\Services\CandidatePerformanceProfileService::class)->masteryLevel($percentage),
                ];
            })
            ->sortBy('score_percentage')
            ->values()
            ->all();
    }

    /**
     * @param \Illuminate\Support\Collection<int, CandidatePerformanceProfile> $profiles
     * @return array<int, array<string, mixed>>
     */
    private function difficultyPerformance($profiles): array
    {
        return $profiles
            ->groupBy(fn (CandidatePerformanceProfile $profile) => $profile->difficulty ?? 'medium')
            ->map(fn ($group, $difficulty) => [
                'difficulty' => str($difficulty)->headline()->toString(),
                'score_percentage' => round($group->avg(fn (CandidatePerformanceProfile $profile) => (float) $profile->score_percentage), 2),
                'total_questions' => $group->sum('total_questions'),
            ])
            ->values()
            ->all();
    }

    /**
     * @param \Illuminate\Support\Collection<int, CandidatePerformanceProfile> $profiles
     * @return array<int, array<string, mixed>>
     */
    private function recommendations($profiles): array
    {
        return $profiles
            ->filter(fn (CandidatePerformanceProfile $profile) => (float) $profile->score_percentage < 70)
            ->sortBy('score_percentage')
            ->take(8)
            ->values()
            ->map(fn (CandidatePerformanceProfile $profile) => [
                'subject' => $profile->subject?->name ?? 'General',
                'topic' => $profile->topic?->name ?? 'Unspecified topic',
                'difficulty' => $profile->difficulty ?? 'medium',
                'score_percentage' => (float) $profile->score_percentage,
                'mastery_level' => $profile->mastery_level,
            ])
            ->all();
    }

    /**
     * @return array<string, mixed>
     */
    private function profileRow(CandidatePerformanceProfile $profile): array
    {
        return [
            'subject' => $profile->subject?->name ?? 'General',
            'topic' => $profile->topic?->name ?? 'Unspecified topic',
            'difficulty' => $profile->difficulty ?? 'medium',
            'total_questions' => $profile->total_questions,
            'correct_answers' => $profile->correct_answers,
            'score_percentage' => (float) $profile->score_percentage,
            'mastery_level' => $profile->mastery_level,
        ];
    }

    /**
     * @return \Illuminate\Support\Collection<int, array<string, mixed>>
     */
    private function markedPaperRows(CandidateExamAttempt $attempt, ?User $user = null)
    {
        $answers = $attempt->answers->keyBy('question_id');
        $assignedSubjectIds = $user?->isTeacher()
            ? $user->assignedSubjects()->pluck('subjects.id')->map(fn ($id) => (string) $id)->all()
            : null;
        $assignedCourseIds = $user?->isFacilitator()
            ? $user->assignedCourses()->pluck('courses.id')->map(fn ($id) => (string) $id)->all()
            : null;
        $assignedModuleIds = $user?->isFacilitator()
            ? $user->assignedModules()->pluck('modules.id')->map(fn ($id) => (string) $id)->all()
            : null;

        return $attempt->papers
            ->sortBy('question_order')
            ->values()
            ->filter(function ($paper) use ($assignedSubjectIds, $assignedCourseIds, $assignedModuleIds): bool {
                if ($assignedSubjectIds !== null) {
                    return in_array((string) $paper->question?->subject_id, $assignedSubjectIds, true);
                }

                if ($assignedCourseIds === null && $assignedModuleIds === null) {
                    return true;
                }

                $bank = $paper->question?->questionBank;

                return ($bank?->course_id && in_array((string) $bank->course_id, $assignedCourseIds ?? [], true))
                    || ($bank?->module_id && in_array((string) $bank->module_id, $assignedModuleIds ?? [], true));
            })
            ->values()
            ->map(function ($paper) use ($answers) {
                $question = $paper->question;
                $answer = $answers->get($paper->question_id);
                $selectedIds = $answer?->selected_option_ids ?? [];
                $options = $question?->options
                    ->sortBy('display_order')
                    ->values()
                    ->map(fn ($option) => [
                        'id' => $option->id,
                        'label' => $option->label,
                        'option_text' => $option->option_text,
                        'selected' => in_array($option->id, $selectedIds, true),
                        'correct' => (bool) $option->is_correct,
                    ])
                    ->all() ?? [];

                return [
                    'question_id' => $paper->question_id,
                    'question' => $question?->stem ?? 'Question',
                    'subject' => $question?->subject?->name ?? $answer?->subject?->name ?? 'General',
                    'marks' => $question?->marks ?? '0.00',
                    'score_awarded' => $answer?->score_awarded,
                    'submitted_at' => $answer?->submitted_at?->toISOString(),
                    'selected_labels' => collect($options)->where('selected', true)->pluck('label')->implode(', '),
                    'correct_labels' => collect($options)->where('correct', true)->pluck('label')->implode(', '),
                    'explanation' => $question?->explanation,
                    'options' => $options,
                ];
            });
    }

    private function scopeFacilitatorQuestionBanks(Builder $query, User $user): void
    {
        $query
            ->where('professional_school_id', $user->professional_school_id)
            ->where(function (Builder $scope) use ($user): void {
                $scope
                    ->whereIn('course_id', $user->assignedCourses()->select('courses.id'))
                    ->orWhereIn('module_id', $user->assignedModules()->select('modules.id'));
            });
    }
}
